on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable, oldstable]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    - name: Test
      run: go test ./...
